# DATA PREPROCESSING/DATA PREPARATION

1. Data Cleaning - drop, fillna with mean, median, mode Imputation, changing dtype
2. Data Transformation
    * If data is CONTINUOUS = Standard Scaler, MinMaxScaler, Robust Scaler
    * If data is DISCRETE   = Label Encoder, One hot Encoder

### 1. Import Necessasary libraries

In [1]:
import pandas as pd

### 2. Import data

In [38]:
weather_data_2010 = pd.read_csv('data_clean.csv')
weather_data_2010

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0             1   41.0    190.0   7.4     67     5    1  2010    67       S
1             2   36.0    118.0   8.0     72     5    2  2010    72       C
2             3   12.0    149.0  12.6     74     5    3  2010    74      PS
3             4   18.0    313.0  11.5     62     5    4  2010    62       S
4             5    NaN      NaN  14.3     56     5    5  2010    56       S
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]

### 3. Data Understanding

#### 3.1 Initial Analysis

In [5]:
weather_data_2010.shape

(158, 10)

In [6]:
weather_data_2010.isna().sum()

Unnamed: 0     0
Ozone         38
Solar.R        7
Wind           0
Temp C         0
Month          0
Day            0
Year           0
Temp           0
Weather        3
dtype: int64

In [7]:
weather_data_2010.dtypes

Unnamed: 0      int64
Ozone         float64
Solar.R       float64
Wind          float64
Temp C         object
Month          object
Day             int64
Year            int64
Temp            int64
Weather        object
dtype: object

In [9]:
weather_data_2010.describe(include = 'all')

,Unnamed: 0,Ozone,Solar.R,Wind,Temp C,Month,Day,Year,Temp,Weather
count,158.000000,120.000000,151.000000,158.000000,158,158,158.000000,158.0,158.000000,155
unique,NaN,NaN,NaN,NaN,41,6,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,81,9,NaN,NaN,NaN,S
freq,NaN,NaN,NaN,NaN,11,34,NaN,NaN,NaN,59
mean,79.500000,41.583333,185.403974,9.957595,NaN,NaN,16.006329,2010.0,77.727848,NaN
std,45.754781,32.620709,88.723103,3.511261,NaN,NaN,8.997166,0.0,9.377877,NaN
min,1.000000,1.000000,7.000000,1.700000,NaN,NaN,1.000000,2010.0,56.000000,NaN
25%,40.250000,18.000000,119.000000,7.400000,NaN,NaN,8.000000,2010.0,72.000000,NaN
50%,79.500000,30.500000,197.000000,9.700000,NaN,NaN,16.000000,2010.0,78.500000,NaN
75%,118.750000,61.500000,257.000000,11.875000,NaN,NaN,24.000000,2010.0,84.000000,NaN
max,158.000000,168.000000,334.000000,20.700000,NaN,NaN,31.000000,2010.0,97.000000,NaN

#### 3.2 EDA

In [11]:
weather_data_2010.Weather.unique()

array(['S', 'C', 'PS', nan], dtype=object)

In [12]:
weather_data_2010.head(50)

    Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0            1   41.0    190.0   7.4     67     5    1  2010    67       S
1            2   36.0    118.0   8.0     72     5    2  2010    72       C
2            3   12.0    149.0  12.6     74     5    3  2010    74      PS
3            4   18.0    313.0  11.5     62     5    4  2010    62       S
4            5    NaN      NaN  14.3     56     5    5  2010    56       S
5            6   28.0      NaN  14.9     66     5    6  2010    66       C
6            7   23.0    299.0   8.6     65     5    7  2010    65      PS
7            8   19.0     99.0  13.8     59     5    8  2010    59       C
8            9    8.0     19.0  20.1     61     5    9  2010    61      PS
9           10    NaN    194.0   8.6     69     5   10  2010    69       S
10          11    7.0      NaN   6.9      C     5   11  2010    74       C
11          12   16.0    256.0   9.7     69     5   12  2010    69      PS
12          13   11.0    290.0   9.2     66     5   13  2010    66       S
13          14   14.0    274.0  10.9     68     5   14  2010    68       S
14          15   18.0     65.0  13.2     58     5   15  2010    58       C
15          16   14.0    334.0  11.5     64     5   16  2010    64       S
16          17   34.0    307.0  12.0     66     5   17  2010    66       S
17          18    6.0     78.0  18.4     57     5   18  2010    57       C
18          19   30.0    322.0  11.5     68     5   19  2010    68      PS
19          20   11.0     44.0   9.7     62     5   20  2010    62       S
20          21    1.0      8.0   9.7     59     5   21  2010    59       S
21          22   11.0    320.0  16.6     73     5   22  2010    73       C
22          23    4.0     25.0   9.7     61     5   23  2010    61      PS
23          24   32.0     92.0  12.0     61   May   24  2010    61       C
24          25    NaN     66.0  16.6     57     5   25  2010    57      PS
25          26    NaN    266.0  14.9     58     5   26  2010    58       C
26          27    NaN      NaN   8.0     57     5   27  2010    57      PS
27          28   23.0     13.0  12.0     67     5   28  2010    67       S
28          29   45.0    252.0  14.9     81     5   29  2010    81       S
29          30  115.0    223.0   5.7     79     5   30  2010    79       C
30          31   37.0    279.0   7.4     76     5   31  2010    76      PS
31          32    NaN    286.0   8.6     78     6    1  2010    78       S
32          33    NaN    287.0   9.7     74     6    2  2010    74       C
33          34    NaN    242.0  16.1     67     6    3  2010    67      PS
34          35    NaN    186.0   9.2     84     6    4  2010    84       C
35          36    NaN    220.0   8.6     85     6    5  2010    85      PS
36          37    NaN    264.0  14.3     79     6    6  2010    79       C
37          38   29.0    127.0   9.7     82     6    7  2010    82      PS
38          39    NaN    273.0   6.9     87     6    8  2010    87       S
39          40   71.0    291.0  13.8     90     6    9  2010    90       S
40          41   39.0    323.0  11.5     87     6   10  2010    87       S
41          42    NaN    259.0  10.9     93     6   11  2010    93       C
42          43    NaN    250.0   9.2     92     6   12  2010    92      PS
43          44   23.0    148.0   8.0     82     6   13  2010    82       S
44          45    NaN    332.0  13.8     80     6   14  2010    80       S
45          46    NaN    322.0  11.5     79     6   15  2010    79       C
46          47   21.0    191.0  14.9     77     6   16  2010    77      PS
47          48   37.0    284.0  20.7     72     6   17  2010    72       C
48          49   20.0     37.0   9.2     65     6   18  2010    65      PS
49          50   12.0    120.0  11.5     73     6   19  2010    73       S

### 4. Data Preparation/Preprocessing

### Step 1: Perform Data Cleaning

In [39]:
del weather_data_2010['Unnamed: 0']

In [14]:
weather_data_2010.isna().sum()

Ozone      38
Solar.R     7
Wind        0
Temp C      0
Month       0
Day         0
Year        0
Temp        0
Weather     3
dtype: int64

In [15]:
weather_data_2010.describe()

            Ozone     Solar.R        Wind         Day    Year        Temp
count  120.000000  151.000000  158.000000  158.000000   158.0  158.000000
mean    41.583333  185.403974    9.957595   16.006329  2010.0   77.727848
std     32.620709   88.723103    3.511261    8.997166     0.0    9.377877
min      1.000000    7.000000    1.700000    1.000000  2010.0   56.000000
25%     18.000000  119.000000    7.400000    8.000000  2010.0   72.000000
50%     30.500000  197.000000    9.700000   16.000000  2010.0   78.500000
75%     61.500000  257.000000   11.875000   24.000000  2010.0   84.000000
max    168.000000  334.000000   20.700000   31.000000  2010.0   97.000000

### PTR: Client - Shashank, approved to go drop the Ozone feature because of more tha 20% of Nan values

In [40]:
del weather_data_2010['Ozone']

In [18]:
weather_data_2010.isna().sum()

Solar.R    7
Wind       0
Temp C     0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

### PTR: Client - Shashank, approved to go with the Median imputaion for Solar.R feature.

In [41]:
weather_data_2010['Solar.R'] = weather_data_2010['Solar.R'].fillna(value=197)

In [21]:
weather_data_2010.isna().sum()

Solar.R    0
Wind       0
Temp C     0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

### PTR: Client - Shashank, approved to go with the Mode imputaion for Weather.

In [42]:
weather_data_2010['Weather'] = weather_data_2010['Weather'].fillna(value = 'S')

In [24]:
weather_data_2010.isna().sum()

Solar.R    0
Wind       0
Temp C     0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

### OBSERVATION:

We can see that there is no Null entries in my data. Now we have to check for the datatypes if it is int or float.

In [25]:
weather_data_2010.dtypes

Solar.R    float64
Wind       float64
Temp C      object
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [27]:
weather_data_2010.head(50)

    Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0     190.0   7.4     67     5    1  2010    67       S
1     118.0   8.0     72     5    2  2010    72       C
2     149.0  12.6     74     5    3  2010    74      PS
3     313.0  11.5     62     5    4  2010    62       S
4     197.0  14.3     56     5    5  2010    56       S
5     197.0  14.9     66     5    6  2010    66       C
6     299.0   8.6     65     5    7  2010    65      PS
7      99.0  13.8     59     5    8  2010    59       C
8      19.0  20.1     61     5    9  2010    61      PS
9     194.0   8.6     69     5   10  2010    69       S
10    197.0   6.9      C     5   11  2010    74       C
11    256.0   9.7     69     5   12  2010    69      PS
12    290.0   9.2     66     5   13  2010    66       S
13    274.0  10.9     68     5   14  2010    68       S
14     65.0  13.2     58     5   15  2010    58       C
15    334.0  11.5     64     5   16  2010    64       S
16    307.0  12.0     66     5   17  2010    66       S
17     78.0  18.4     57     5   18  2010    57       C
18    322.0  11.5     68     5   19  2010    68      PS
19     44.0   9.7     62     5   20  2010    62       S
20      8.0   9.7     59     5   21  2010    59       S
21    320.0  16.6     73     5   22  2010    73       C
22     25.0   9.7     61     5   23  2010    61      PS
23     92.0  12.0     61   May   24  2010    61       C
24     66.0  16.6     57     5   25  2010    57      PS
25    266.0  14.9     58     5   26  2010    58       C
26    197.0   8.0     57     5   27  2010    57      PS
27     13.0  12.0     67     5   28  2010    67       S
28    252.0  14.9     81     5   29  2010    81       S
29    223.0   5.7     79     5   30  2010    79       C
30    279.0   7.4     76     5   31  2010    76      PS
31    286.0   8.6     78     6    1  2010    78       S
32    287.0   9.7     74     6    2  2010    74       C
33    242.0  16.1     67     6    3  2010    67      PS
34    186.0   9.2     84     6    4  2010    84       C
35    220.0   8.6     85     6    5  2010    85      PS
36    264.0  14.3     79     6    6  2010    79       C
37    127.0   9.7     82     6    7  2010    82      PS
38    273.0   6.9     87     6    8  2010    87       S
39    291.0  13.8     90     6    9  2010    90       S
40    323.0  11.5     87     6   10  2010    87       S
41    259.0  10.9     93     6   11  2010    93       C
42    250.0   9.2     92     6   12  2010    92      PS
43    148.0   8.0     82     6   13  2010    82       S
44    332.0  13.8     80     6   14  2010    80       S
45    322.0  11.5     79     6   15  2010    79       C
46    191.0  14.9     77     6   16  2010    77      PS
47    284.0  20.7     72     6   17  2010    72       C
48     37.0   9.2     65     6   18  2010    65      PS
49    120.0  11.5     73     6   19  2010    73       S

In [43]:
weather_data_2010['Temp C'] = pd.to_numeric(arg = weather_data_2010['Temp C'], errors='coerce')
weather_data_2010['Month']  = pd.to_numeric(arg = weather_data_2010['Month'], errors='coerce')

In [34]:
weather_data_2010.head(50)

    Solar.R  Wind  Temp C  Month  Day  Year  Temp Weather
0     190.0   7.4    67.0    5.0    1  2010    67       S
1     118.0   8.0    72.0    5.0    2  2010    72       C
2     149.0  12.6    74.0    5.0    3  2010    74      PS
3     313.0  11.5    62.0    5.0    4  2010    62       S
4     197.0  14.3    56.0    5.0    5  2010    56       S
5     197.0  14.9    66.0    5.0    6  2010    66       C
6     299.0   8.6    65.0    5.0    7  2010    65      PS
7      99.0  13.8    59.0    5.0    8  2010    59       C
8      19.0  20.1    61.0    5.0    9  2010    61      PS
9     194.0   8.6    69.0    5.0   10  2010    69       S
10    197.0   6.9     NaN    5.0   11  2010    74       C
11    256.0   9.7    69.0    5.0   12  2010    69      PS
12    290.0   9.2    66.0    5.0   13  2010    66       S
13    274.0  10.9    68.0    5.0   14  2010    68       S
14     65.0  13.2    58.0    5.0   15  2010    58       C
15    334.0  11.5    64.0    5.0   16  2010    64       S
16    307.0  12.0    66.0    5.0   17  2010    66       S
17     78.0  18.4    57.0    5.0   18  2010    57       C
18    322.0  11.5    68.0    5.0   19  2010    68      PS
19     44.0   9.7    62.0    5.0   20  2010    62       S
20      8.0   9.7    59.0    5.0   21  2010    59       S
21    320.0  16.6    73.0    5.0   22  2010    73       C
22     25.0   9.7    61.0    5.0   23  2010    61      PS
23     92.0  12.0    61.0    NaN   24  2010    61       C
24     66.0  16.6    57.0    5.0   25  2010    57      PS
25    266.0  14.9    58.0    5.0   26  2010    58       C
26    197.0   8.0    57.0    5.0   27  2010    57      PS
27     13.0  12.0    67.0    5.0   28  2010    67       S
28    252.0  14.9    81.0    5.0   29  2010    81       S
29    223.0   5.7    79.0    5.0   30  2010    79       C
30    279.0   7.4    76.0    5.0   31  2010    76      PS
31    286.0   8.6    78.0    6.0    1  2010    78       S
32    287.0   9.7    74.0    6.0    2  2010    74       C
33    242.0  16.1    67.0    6.0    3  2010    67      PS
34    186.0   9.2    84.0    6.0    4  2010    84       C
35    220.0   8.6    85.0    6.0    5  2010    85      PS
36    264.0  14.3    79.0    6.0    6  2010    79       C
37    127.0   9.7    82.0    6.0    7  2010    82      PS
38    273.0   6.9    87.0    6.0    8  2010    87       S
39    291.0  13.8    90.0    6.0    9  2010    90       S
40    323.0  11.5    87.0    6.0   10  2010    87       S
41    259.0  10.9    93.0    6.0   11  2010    93       C
42    250.0   9.2    92.0    6.0   12  2010    92      PS
43    148.0   8.0    82.0    6.0   13  2010    82       S
44    332.0  13.8    80.0    6.0   14  2010    80       S
45    322.0  11.5    79.0    6.0   15  2010    79       C
46    191.0  14.9    77.0    6.0   16  2010    77      PS
47    284.0  20.7    72.0    6.0   17  2010    72       C
48     37.0   9.2    65.0    6.0   18  2010    65      PS
49    120.0  11.5    73.0    6.0   19  2010    73       S

In [35]:
weather_data_2010.dtypes

Solar.R    float64
Wind       float64
Temp C     float64
Month      float64
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [32]:
weather_data_2010['Temp C'].mean()

77.7515923566879

In [48]:
weather_data_2010['Temp C'] = weather_data_2010['Temp C'].fillna(value=77.75)
weather_data_2010['Month']  = weather_data_2010['Month'].fillna(value = 5).astype('int')

In [49]:
weather_data_2010.dtypes

Solar.R    float64
Wind       float64
Temp C     float64
Month        int32
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [50]:
weather_data_2010

     Solar.R  Wind  Temp C  Month  Day  Year  Temp Weather
0      190.0   7.4    67.0      5    1  2010    67       S
1      118.0   8.0    72.0      5    2  2010    72       C
2      149.0  12.6    74.0      5    3  2010    74      PS
3      313.0  11.5    62.0      5    4  2010    62       S
4      197.0  14.3    56.0      5    5  2010    56       S
..       ...   ...     ...    ...  ...   ...   ...     ...
153    190.0   7.4    67.0      5    1  2010    67       C
154    193.0   6.9    70.0      9   26  2010    70      PS
155    145.0  13.2    77.0      9   27  2010    77       S
156    191.0  14.3    75.0      9   28  2010    75       S
157    131.0   8.0    76.0      9   29  2010    76       C

[158 rows x 8 columns]

In [51]:
del weather_data_2010['Temp C']

In [52]:
weather_data_2010.dtypes

Solar.R    float64
Wind       float64
Month        int32
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [53]:
weather_data_2010.isna().sum()

Solar.R    0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

In [54]:
del weather_data_2010['Year']

In [56]:
weather_data_2010.head(50)

    Solar.R  Wind  Month  Day  Temp Weather
0     190.0   7.4      5    1    67       S
1     118.0   8.0      5    2    72       C
2     149.0  12.6      5    3    74      PS
3     313.0  11.5      5    4    62       S
4     197.0  14.3      5    5    56       S
5     197.0  14.9      5    6    66       C
6     299.0   8.6      5    7    65      PS
7      99.0  13.8      5    8    59       C
8      19.0  20.1      5    9    61      PS
9     194.0   8.6      5   10    69       S
10    197.0   6.9      5   11    74       C
11    256.0   9.7      5   12    69      PS
12    290.0   9.2      5   13    66       S
13    274.0  10.9      5   14    68       S
14     65.0  13.2      5   15    58       C
15    334.0  11.5      5   16    64       S
16    307.0  12.0      5   17    66       S
17     78.0  18.4      5   18    57       C
18    322.0  11.5      5   19    68      PS
19     44.0   9.7      5   20    62       S
20      8.0   9.7      5   21    59       S
21    320.0  16.6      5   22    73       C
22     25.0   9.7      5   23    61      PS
23     92.0  12.0      5   24    61       C
24     66.0  16.6      5   25    57      PS
25    266.0  14.9      5   26    58       C
26    197.0   8.0      5   27    57      PS
27     13.0  12.0      5   28    67       S
28    252.0  14.9      5   29    81       S
29    223.0   5.7      5   30    79       C
30    279.0   7.4      5   31    76      PS
31    286.0   8.6      6    1    78       S
32    287.0   9.7      6    2    74       C
33    242.0  16.1      6    3    67      PS
34    186.0   9.2      6    4    84       C
35    220.0   8.6      6    5    85      PS
36    264.0  14.3      6    6    79       C
37    127.0   9.7      6    7    82      PS
38    273.0   6.9      6    8    87       S
39    291.0  13.8      6    9    90       S
40    323.0  11.5      6   10    87       S
41    259.0  10.9      6   11    93       C
42    250.0   9.2      6   12    92      PS
43    148.0   8.0      6   13    82       S
44    332.0  13.8      6   14    80       S
45    322.0  11.5      6   15    79       C
46    191.0  14.9      6   16    77      PS
47    284.0  20.7      6   17    72       C
48     37.0   9.2      6   18    65      PS
49    120.0  11.5      6   19    73       S

### 4.2 Data Transformation
* If data is CONTINUOUS = Standard Scaler, MinMaxScaler, Robust Scaler
* If data is DISCRETE   = Label Encoder, One hot Encoder

In [60]:
weather_data_2010_2 = weather_data_2010.copy()
weather_data_2010_2

     Solar.R  Wind  Month  Day  Temp Weather
0      190.0   7.4      5    1    67       S
1      118.0   8.0      5    2    72       C
2      149.0  12.6      5    3    74      PS
3      313.0  11.5      5    4    62       S
4      197.0  14.3      5    5    56       S
..       ...   ...    ...  ...   ...     ...
153    190.0   7.4      5    1    67       C
154    193.0   6.9      9   26    70      PS
155    145.0  13.2      9   27    77       S
156    191.0  14.3      9   28    75       S
157    131.0   8.0      9   29    76       C

[158 rows x 6 columns]

#### Label Encoding Technique

It can be performed by using a **library support - sklearn** or **creating a user-defined function**.

In [65]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
weather_data_2010_2['Encoded_Weather'] = le.fit_transform(weather_data_2010_2['Weather'])
weather_data_2010_2.head(20)

    Solar.R  Wind  Month  Day  Temp Weather  Encoded_Weather
0     190.0   7.4      5    1    67       S                2
1     118.0   8.0      5    2    72       C                0
2     149.0  12.6      5    3    74      PS                1
3     313.0  11.5      5    4    62       S                2
4     197.0  14.3      5    5    56       S                2
5     197.0  14.9      5    6    66       C                0
6     299.0   8.6      5    7    65      PS                1
7      99.0  13.8      5    8    59       C                0
8      19.0  20.1      5    9    61      PS                1
9     194.0   8.6      5   10    69       S                2
10    197.0   6.9      5   11    74       C                0
11    256.0   9.7      5   12    69      PS                1
12    290.0   9.2      5   13    66       S                2
13    274.0  10.9      5   14    68       S                2
14     65.0  13.2      5   15    58       C                0
15    334.0  11.5      5   16    64       S                2
16    307.0  12.0      5   17    66       S                2
17     78.0  18.4      5   18    57       C                0
18    322.0  11.5      5   19    68      PS                1
19     44.0   9.7      5   20    62       S                2

In [66]:
del weather_data_2010_2['Weather']

In [67]:
weather_data_2010_2

     Solar.R  Wind  Month  Day  Temp  Encoded_Weather
0      190.0   7.4      5    1    67                2
1      118.0   8.0      5    2    72                0
2      149.0  12.6      5    3    74                1
3      313.0  11.5      5    4    62                2
4      197.0  14.3      5    5    56                2
..       ...   ...    ...  ...   ...              ...
153    190.0   7.4      5    1    67                0
154    193.0   6.9      9   26    70                1
155    145.0  13.2      9   27    77                2
156    191.0  14.3      9   28    75                2
157    131.0   8.0      9   29    76                0

[158 rows x 6 columns]

In [68]:
weather_data_2010_2.dtypes

Solar.R            float64
Wind               float64
Month                int32
Day                  int64
Temp                 int64
Encoded_Weather      int32
dtype: object

#### OneHotEncoding Technique

Can be achieved using any of these 2 libraries:

**1. sklearn - OneHotEncoder**

**2. Pandas  - get_dummies()**

### Pandas - OHE

In [71]:
weather_data_2010_3 = weather_data_2010.copy()
weather_data_2010_3

     Solar.R  Wind  Month  Day  Temp Weather
0      190.0   7.4      5    1    67       S
1      118.0   8.0      5    2    72       C
2      149.0  12.6      5    3    74      PS
3      313.0  11.5      5    4    62       S
4      197.0  14.3      5    5    56       S
..       ...   ...    ...  ...   ...     ...
153    190.0   7.4      5    1    67       C
154    193.0   6.9      9   26    70      PS
155    145.0  13.2      9   27    77       S
156    191.0  14.3      9   28    75       S
157    131.0   8.0      9   29    76       C

[158 rows x 6 columns]

In [74]:
weather_data_2010_3 = pd.get_dummies(data = weather_data_2010_3,columns=['Weather'])
weather_data_2010_3

     Solar.R  Wind  Month  Day  Temp  Weather_C  Weather_PS  Weather_S
0      190.0   7.4      5    1    67          0           0          1
1      118.0   8.0      5    2    72          1           0          0
2      149.0  12.6      5    3    74          0           1          0
3      313.0  11.5      5    4    62          0           0          1
4      197.0  14.3      5    5    56          0           0          1
..       ...   ...    ...  ...   ...        ...         ...        ...
153    190.0   7.4      5    1    67          1           0          0
154    193.0   6.9      9   26    70          0           1          0
155    145.0  13.2      9   27    77          0           0          1
156    191.0  14.3      9   28    75          0           0          1
157    131.0   8.0      9   29    76          1           0          0

[158 rows x 8 columns]

### Using sklearn's OHE

In [78]:
weather_data_2010_4 = weather_data_2010.copy()
weather_data_2010_4

     Solar.R  Wind  Month  Day  Temp Weather
0      190.0   7.4      5    1    67       S
1      118.0   8.0      5    2    72       C
2      149.0  12.6      5    3    74      PS
3      313.0  11.5      5    4    62       S
4      197.0  14.3      5    5    56       S
..       ...   ...    ...  ...   ...     ...
153    190.0   7.4      5    1    67       C
154    193.0   6.9      9   26    70      PS
155    145.0  13.2      9   27    77       S
156    191.0  14.3      9   28    75       S
157    131.0   8.0      9   29    76       C

[158 rows x 6 columns]

In [79]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
weather_data_2010_4['Encoded_Weather'] = ohe.fit_transform(weather_data_2010_4['Weather'])
weather_data_2010_4.head(20)

ValueError: Expected 2D array, got 1D array instead:
array=['S' 'C' 'PS' 'S' 'S' 'C' 'PS' 'C' 'PS' 'S' 'C' 'PS' 'S' 'S' 'C' 'S' 'S'
 'C' 'PS' 'S' 'S' 'C' 'PS' 'C' 'PS' 'C' 'PS' 'S' 'S' 'C' 'PS' 'S' 'C' 'PS'
 'C' 'PS' 'C' 'PS' 'S' 'S' 'S' 'C' 'PS' 'S' 'S' 'C' 'PS' 'C' 'PS' 'S' 'S'
 'S' 'C' 'PS' 'S' 'C' 'PS' 'C' 'PS' 'S' 'S' 'S' 'C' 'PS' 'S' 'S' 'C' 'C'
 'PS' 'C' 'PS' 'S' 'S' 'S' 'C' 'PS' 'S' 'S' 'C' 'PS' 'C' 'S' 'S' 'C' 'PS'
 'PS' 'C' 'S' 'S' 'C' 'PS' 'C' 'PS' 'S' 'PS' 'S' 'S' 'C' 'C' 'PS' 'C' 'PS'
 'S' 'S' 'S' 'C' 'C' 'C' 'PS' 'C' 'PS' 'S' 'S' 'C' 'PS' 'C' 'PS' 'S' 'S'
 'S' 'S' 'S' 'C' 'C' 'PS' 'C' 'PS' 'S' 'S' 'S' 'C' 'PS' 'C' 'PS' 'S' 'S'
 'PS' 'PS' 'S' 'PS' 'S' 'C' 'PS' 'PS' 'S' 'S' 'C' 'PS' 'C' 'PS' 'S' 'PS'
 'S' 'C' 'PS' 'S' 'S' 'C'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.